# This file is automatically generated by Catapult each time CDesignChecker is
# is launched from Catapult. Any user-applied edits will be overwritten.

set ::env(SLEC_GCC_HOME) /RAID2/cad/mentor/Catapult/2023.2/Mgc_home/pkgs/dcs_gcc/usr
# Property checks

# add Verification Mode settings
set_verification_mode -c_property_checks 

# Clear all settings
config_property_checks -disable -all
# Enable rules
config_property_checks -enable -abr -severity error 
config_property_checks -enable -abw -severity error 
config_property_checks -enable -acc -severity warning 
config_property_checks -enable -acs -severity warning 
config_property_checks -enable -aic -severity warning 
config_property_checks -enable -als -severity warning 
config_property_checks -enable -aob -severity error 
config_property_checks -enable -apt -severity info 
config_property_checks -enable -awe -severity warning 
config_property_checks -enable -cas -severity error 
config_property_checks -enable -cbu -severity warning 
config_property_checks -enable -ccc -severity warning 
config_property_checks -enable -cgr -severity warning 
config_property_checks -enable -cia -severity warning 
config_property_checks -enable -cmc -severity info 
config_property_checks -enable -cns -severity warning 
config_property_checks -enable -cwb -severity warning 
config_property_checks -enable -dbz -severity error 
config_property_checks -enable -diu -severity warning 
config_property_checks -enable -fvi -severity warning 
config_property_checks -enable -fxd -severity warning 
config_property_checks -enable -ise -severity error 
config_property_checks -enable -lrc -severity info 
config_property_checks -enable -mdb -severity warning 
config_property_checks -enable -mxs -severity info 
config_property_checks -enable -nco -severity warning 
config_property_checks -enable -osa -severity warning 
config_property_checks -enable -ovl -severity error 
config_property_checks -enable -pdd -severity warning 
config_property_checks -enable -riu -severity warning 
config_property_checks -enable -rrt -severity error 
config_property_checks -enable -sat -severity warning 
config_property_checks -enable -stf -severity info 
config_property_checks -enable -sud -severity warning 
config_property_checks -enable -umr -severity error 

# Symbolic Memory Control
set_global symbolic_memory_threshold_size 256

# verification effort
set_verification_effort -medium
set_global report_undecided_solver_properties 1


