// ----------------------------------------------------------------------------
// SLEC wrapper around original function
//
//    HLS version: 8.2
//   SLEC version: SLEC 2023.2
//
//   Generated by: asoc020
// Generated date: Tue Mar 26 16:54:38 CST 2024
//
// ----------------------------------------------------------------------------
//

#ifndef INCLUDED_SPEC_WRAPPER_H
#define INCLUDED_SPEC_WRAPPER_H

#ifndef SLEC_TB_HELPERS
#define SLEC_TB_HELPERS
#ifdef SLEC_CAT2SLEC_TB
#include <iostream>
extern bool gen_tb_debug_output;
#define _TB_NAME sc_core::sc_get_current_process_b()->get_parent()->basename()
#define _TB_TIME() if (gen_tb_debug_output) std::cout << "@" << sc_time_stamp() << std::endl
#define _TB_SHOW(x) if (gen_tb_debug_output) std::cout << "@" << sc_time_stamp() << " in(" << _TB_NAME << "): " << x << std::endl
#else //SLEC_CAT2SLEC_TB
#define _TB_TIME()
#define _TB_SHOW(x)
#endif //SLEC_CAT2SLEC_TB
#endif //SLEC_TB_HELPERS

// Includes
#include "fir.h"
#include <systemc.h>
#include <ac_int.h>
#include <ac_channel.h>
#include "cpc_input_ac_channel_adapter.h"

class spec_wrapper : public sc_module
{
public:

    // Interface Ports
    sc_in<bool> clk;
    sc_in<bool> rst;
    sc_in< sc_lv<8> > slecIN_input_idx_0;
    sc_in< sc_lv<1> > slecIN_input_counter_reset_idx_0;
    sc_in< sc_lv<64> > slecIN_coeffs_idx_0;
    sc_out< sc_lv<8> > slecOUT_output_idx_0;
#ifdef SLEC_FLAT_CAT2SLEC_TB
    sc_in< bool > tb_run_dut;
    sc_in< bool > tb_latch_nonstream;
#endif //SLEC_FLAT_CAT2SLEC_TB
#ifdef SLEC_CHANNEL_CAT2SLEC_TB
    sc_in< bool > input_rdy;
    sc_out< bool > input_vld;
    sc_signal< sc_lv<1> > tb_reset_istream_counters;
    sc_signal< sc_lv<1> > tb_reset_ostream_counters;
#endif //SLEC_CHANNEL_CAT2SLEC_TB

    // Data Objects
    sc_signal< bool > clk_neg;
    sc_signal< bool > rst_neg;
    sc_signal< sc_lv<8> > net_dout_input;
    sc_signal< bool > Calypto_transaction_done;
    int _Calypto_function_call_counter;
    fir p_this;
    static ac_channel<ac_int<8, true > > input;
    ac_int<8, true > coeffs[8];
    static ac_channel<ac_int<8, true > > output;
    sc_signal< bool > net_always_zero;
    sc_signal< bool > net_always_one;

    // Module Instance Declaration
    input_ac_channel_adapter<8,1> INST_adapter_input;

    // Declare processes
    void set_constants();
    void generate_clk_rst();
    void doit();
    void process_input();
    void process_output();

#ifndef SLEC_CHANNEL_CAT2SLEC_TB

#else //SLEC_CHANNEL_CAT2SLEC_TB
    void counter_reset();

#endif //SLEC_CHANNEL_CAT2SLEC_TB
    // Constructor
    SC_HAS_PROCESS(spec_wrapper);
    spec_wrapper(
        sc_module_name name
    ) :
        INST_adapter_input("INST_adapter_input")
    {
        // Instance Binding
        INST_adapter_input.clk(clk);
        INST_adapter_input.design_rst(rst);
        INST_adapter_input.din[0](slecIN_input_idx_0);
        INST_adapter_input.dout(net_dout_input);
    #ifndef SLEC_CHANNEL_CAT2SLEC_TB
        INST_adapter_input.counter_rst(slecIN_input_counter_reset_idx_0);
        INST_adapter_input.ready(input.rdy);
    #else //SLEC_CHANNEL_CAT2SLEC_TB
        INST_adapter_input.counter_rst(tb_reset_istream_counters);
        INST_adapter_input.ready(input_rdy);
        INST_adapter_input.valid(input_vld);
    #endif //SLEC_CHANNEL_CAT2SLEC_TB


        // Register processes
        SC_METHOD(set_constants);
        sensitive << clk.pos();

        SC_METHOD(generate_clk_rst);
        sensitive << clk;
        sensitive << rst;

        SC_CTHREAD(doit,clk.pos());
        reset_signal_is(rst,true);

        SC_METHOD(process_input);
        #ifndef SLEC_CHANNEL_CAT2SLEC_TB
        sensitive << net_dout_input;
        #else //SLEC_CHANNEL_CAT2SLEC_TB
        sensitive << clk.neg();
        #endif //SLEC_CHANNEL_CAT2SLEC_TB

        SC_METHOD(process_output);
        #ifndef SLEC_CHANNEL_CAT2SLEC_TB
        sensitive << output.dat;
        #else //SLEC_CHANNEL_CAT2SLEC_TB
        sensitive << clk.neg();
        #endif //SLEC_CHANNEL_CAT2SLEC_TB

#ifndef SLEC_CHANNEL_CAT2SLEC_TB
#else //SLEC_CHANNEL_CAT2SLEC_TB
        SC_METHOD(counter_reset);
        sensitive << clk.pos();

#endif //SLEC_CHANNEL_CAT2SLEC_TB

        // Other constructor statements

    }

    ~spec_wrapper()
    {
    }

    // C++ class functions
    public:
        void resetData();
    public:
        void readData();
    public:
        void writeData();
};
#endif
